### ISSUE TITLE
Update the merged ppt pdf

### ISSUE THREAD

**Issue by animesh-sri-98** [Iamsatishsharma/BITS-MTech-Software-engineering#2]
It would be great if you can update the merged pdf files to include all the modules. It'll help everyone to prepare for the end sem exams.

Thanks!

**Comment by iamsatishsharma** [comment]
Hi Animesh, 
Good Day!
I am currently working on it and plan to upload it sometime over the upcoming weekend.

Regards,
Satish

**Comment by animesh-sri-98** [comment]
Great to know that. Thanks Satish.
